### ISSUE TITLE
Issue setting up project with dirt-cli on Setting up Django... step

### ISSUE THREAD

**Issue by npmSteven** [saiforceone/dirt-cli#2]
```
$ npx @saiforceone/dirt-cli


______ ___________ _____   _____  _     _____
|  _  \_   _| ___ \_   _| /  __ \| |   |_   _|
| | | | | | | |_/ / | |   | /  \/| |     | |
| | | | | | |    /  | |   | |    | |     | |
| |/ / _| |_| |\ \  | |   | \__/\| |_____| |_
|___/  \___/\_| \_| \_/    \____/\_____/\___/

 Let's get D.I.R.T-y...

 Before we can scaffold your project, we have a few questions

? What should we call this project? test
? What should we call this project? test
? Select a frontend framework / library (Use arrow keys)
? Select a frontend framework / library react
? Would you like to use StorybookJS? (y/N)
? Would you like to use StorybookJS? No
? Would you like to have git initialized? (y/N)
? Would you like to have git initialized? No
? Show verbose logs? (y/N)
? Show verbose logs? No

Setting up your D.I.R.T Stack application...
Setting up project with log mode: Quiet

- Setting up Django...
× Failed to setup Django. See below.
Error: Django scaffold error: ENOENT: no such file or directory, access 'C:\Users\user\.virtualenvs\ten\python3'
```

**Comment by saiforceone** [comment]
I have encountered the same problem in the new Windows env that I set-up and I will be working on the solution. Stay tuned for an update that addresses the Windows setup issue.

**Comment by saiforceone** [comment]
Progress update: the CLI is now able to scaffold project for Windows. There are a few things left to resolve and code to clean up. A release with all the fixes will be out in the next few days
![image](https://user-images.githubusercontent.com/97003335/225828188-84a11f2c-c350-4e76-84b6-bac9e941f5a4.png)

**Comment by saiforceone** [comment]
![image](https://user-images.githubusercontent.com/97003335/226145302-d958f28c-472d-41f5-a06d-50c2e8c52ecd.png)

![image](https://user-images.githubusercontent.com/97003335/226145368-d5dd70e6-887f-495e-a5ef-57837f759af7.png)

@npmSteven The Windows issue has now been resolved. Please try scaffolding the project again. The command should use the latest version from NPM. Thanks for helping test the windows scaffolding process and be sure to let me know if you run into other issues.
