### ISSUE TITLE
PascalCasing

### ISSUE THREAD

**Issue by Yumshot** [saiforceone/dirt-cli#5]
when running the npx command and giving the package name a PascalCasing. yumshot@x:~/Documents/Repos/TestTools$ npx @saiforceone/dirt-cli

______ ___________ _____   _____  _     _____
|  _  \_   _| ___ \_   _| /  __ \| |   |_   _|
| | | | | | | |_/ / | |   | /  \/| |     | |
| | | | | | |    /  | |   | |    | |     | |
| |/ / _| |_| |\ \  | |   | \__/\| |_____| |_
|___/  \___/\_| \_| \_/    \____/\_____/\___/

 Let's get D.I.R.T-y...

 Before we can scaffold your project, we have a few questions

? What should we call this project? YumTools
? Select a frontend framework / library react
? Would you like to use StorybookJS? No
? Would you like to have git initialized? Yes
? Show verbose logs? Yes

Setting up your D.I.R.T Stack application...
Setting up project with log mode: Verbose

[info] » Setting up Django project...
[info] » executing scaffoldDjango...
[info] » creating project with name: YumTools
[info] » in directory:  /home/yumshot/Documents/Repos/TestTools/YumTools
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v19.7.0

After testing, camelCase and lowercase work perfectly fine.

**Comment by saiforceone** [comment]
Currently unable to reproduce the issue on `Ubuntu 22.04 LTS` using the options specified above. I will leave this open so that we can gather more information.

More details about my environment
`NodeJs v16.17.0`
`npm v8.15.0`
`Python 3.10.9`

**Comment by Yumshot** [comment]
I was unable to produce the bug again, moved OS to arch linux 
  ```
  OS - Garuda Linux x86_64
  KERN - 6.2.8-zen1-1-zen
  WM - i3 (X11)
  SHELL - bash 5.1.16
  TERM - pipenv
  ```
  I will note though that the pip install version of pipenv did not work, and I had to get the repo from an AUR to get it working. Im sure it could just be an env variable, however might be something to keep a note of for future / possible distro specific issues
